# -*- coding: utf-8 -*-
"""distilbert_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9XVlObPUKw2tnh5Yoreo43STncNogxu
"""

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset
from transformers import (
    DistilBertTokenizer,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, f1_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Set dataset path
DATASET_PATH = "/content/dataset.csv"

df = pd.read_csv(DATASET_PATH)

labels = sorted(df['label'].unique())
label_map = {old: new for new, old in enumerate(labels)}

label_counts = df["label"].value_counts().sort_index().reset_index()
label_counts.columns = ["label", "count"]
print(label_counts)

# Set random seed for reproduceability
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# Create custom dataset class for Pytorch
class QueryDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Split data into Train, Validation test
# First split: Train+Val (85%) and Test (15%)
train_val_df, test_df = train_test_split(
    df,
    test_size=0.15,
    random_state=SEED,
    stratify=df['label']
)

# Second split: Train (70% of total) and Val (15% of total)
# 0.176 of 85% is approximately 15% of the whole dataset
train_df, val_df = train_test_split(
    train_val_df,
    test_size=0.176,
    random_state=SEED,
    stratify=train_val_df['label']
)

# Tokenization
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

# Tokenization helper
def tokenize(texts):
    return tokenizer(texts, truncation=True, padding=True, max_length=128)

# Create PyTorch datasets for all three splitss
train_ds = QueryDataset(tokenize(train_df['text'].tolist()), train_df['label'].tolist())
val_ds = QueryDataset(tokenize(val_df['text'].tolist()), val_df['label'].tolist())
test_ds = QueryDataset(tokenize(test_df['text'].tolist()), test_df['label'].tolist())

# Loading distilBERT
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=len(labels))

# Define Training Arguments
# Set f1 as the metric and 10 epochs
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    warmup_steps=100,
    weight_decay=0.01,
    logging_dir='./logs',
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none"
)

# Define f1-score and accuracy as metrics
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    f1 = f1_score(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {'accuracy': acc, 'f1': f1}

# Initialize trainer for model with early stopping
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

# Fine-tune the model
trainer.train()

trainer.evaluate()

# Final Evaluation on the Unseen Test Set
print("\n" + "="*30)
print("FINAL TEST SET EVALUATION")
print("="*30)
predictions = trainer.predict(test_ds)
y_true = predictions.label_ids
y_pred = predictions.predictions.argmax(-1)

reverse_map = {v: k for k, v in label_map.items()}
target_names = [f"Class {reverse_map[i]}" for i in range(len(labels))]

print(classification_report(y_true, y_pred, target_names=target_names))

# Save the best model
model.save_pretrained('./final_intent_model')
tokenizer.save_pretrained('./final_intent_model')
print("Model saved to './final_intent_model'")

# Plot confusion matrix between actual and predicted labels
def plot_confusion_matrix(y_true, y_pred, label_map):
    # Create the matrix
    cm = confusion_matrix(y_true, y_pred)

    # Names of the classes in the correct order
    reverse_map = {v: k for k, v in label_map.items()}
    class_names = [f"Class {reverse_map[i]}" for i in range(len(label_map))]

    # Plotting
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)

    plt.title('Confusion Matrix: Multi Classification')
    plt.ylabel('Actual Label')
    plt.xlabel('Predicted Label')
    plt.xticks(rotation=45)
    plt.tight_layout()

    # Save the plot
    plt.savefig('confusion_matrix.png')

plot_confusion_matrix(y_true, y_pred, label_map)